/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    ADrawer: typeof import('@arco-design/web-vue')['Drawer']
    AOption: typeof import('@arco-design/web-vue')['Option']
    ASelect: typeof import('@arco-design/web-vue')['Select']
    ATextarea: typeof import('@arco-design/web-vue')['Textarea']
    CustomFormItem: typeof import('./src/components/list/customFormItem.vue')['default']
    CustomHeader: typeof import('./src/components/customHeader.vue')['default']
    CustomList: typeof import('./src/components/pdf/customList.vue')['default']
    Draggable: typeof import('./src/components/layout/draggable.vue')['default']
    Drawer: typeof import('./src/components/list/drawer.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckboxButton: typeof import('element-plus/es')['ElCheckboxButton']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopconfirm: typeof import('element-plus/es')['ElPopconfirm']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FormItem: typeof import('./src/components/list/formItem.vue')['default']
    Header: typeof import('./src/components/list/header.vue')['default']
    ImageDialog: typeof import('./src/components/list/imageDialog.vue')['default']
    ImageItem: typeof import('./src/components/list/imageItem.vue')['default']
    List: typeof import('./src/components/pdf/list.vue')['default']
    ModelAnalysis: typeof import('./src/components/list/modelAnalysis.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tooth: typeof import('./src/components/list/tooth.vue')['default']
  }
}
