/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/template/button.vue')['default']
    Checkbox: typeof import('./src/components/list/checkbox.vue')['default']
    ChooseTooth: typeof import('./src/components/list/chooseTooth.vue')['default']
    CustomFormItem: typeof import('./src/components/list/customFormItem.vue')['default']
    CustomHeader: typeof import('./src/components/customHeader.vue')['default']
    CustomList: typeof import('./src/components/pdf/customList.vue')['default']
    Draggable: typeof import('./src/components/layout/draggable.vue')['default']
    DraggableTool: typeof import('./src/components/layout/draggableTool.vue')['default']
    Drawer: typeof import('./src/components/list/drawer.vue')['default']
    EvaluateList: typeof import('./src/components/evaluatePdf/evaluateList.vue')['default']
    FormItem: typeof import('./src/components/list/formItem.vue')['default']
    Header: typeof import('./src/components/list/header.vue')['default']
    ImageDialog: typeof import('./src/components/list/imageDialog.vue')['default']
    ImageItem: typeof import('./src/components/list/imageItem.vue')['default']
    LayoutChooseTooth: typeof import('./src/components/layout/layoutChooseTooth.vue')['default']
    List: typeof import('./src/components/pdf/list.vue')['default']
    ModelAnalysis: typeof import('./src/components/list/modelAnalysis.vue')['default']
    Option: typeof import('./src/components/list/option.vue')['default']
    OptionWithTooth: typeof import('./src/components/list/OptionWithTooth.vue')['default']
    PreviewImage: typeof import('./src/components/list/previewImage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tooth: typeof import('./src/components/list/tooth.vue')['default']
  }
}
